version: '3'
services:
  service_1:
    container_name: api_service_1
    build: ./service_1
    volumes:
      - ./:/tcc
    ports:
      - 3000:3000
    command:
      - 'nodemon'
      - './service_1/src/server.js'
    environment:
      - NODE_AMBIENTE=docker
    links:
      - mongo
    depends_on:
      - mongo
  service_2:
    container_name: api_service_2
    build: ./service_2
    volumes:
      - ./:/tcc
    ports:
      - 5000:5000
    command:
      - 'python'
      - './server/app.py'
  service_core:
    container_name: api_service_core
    build: ./service_core
    volumes:
      - ./:/tcc
    ports:
      - 3001:3001
    command:
      - 'nodemon'
      - './src/server.js'
    environment:
      - NODE_AMBIENTE=docker
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db
  service_web:
    image: nginx:latest
    container_name: api_service_web
    restart: always
    ports:
      - "8080:80"
      - "80:8080"
    volumes:
      - ./service_web/dist:/usr/share/nginx/html
      - ./service_web/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./:/tcc

volumes:
  data:
    external: false
  tcc: